force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingTriggerHandler.cls
public with sharing class BookingTriggerHandler extends TriggerHandler{
    
    override public void beforeInsert(){
        BookingTriggerHandlerService.validateBookingOverlap(Trigger.new);
    }

    override public void beforeUpdate(){
        List<Booking__c> bookings = (List<Booking__c>)Trigger.new;
        Map<Id,Booking__c> oldBookingMap = (Map<Id,Booking__c>)Trigger.oldMap;
        List<Booking__c> bookingsToValidate = new List<Booking__c>();
        For(Booking__c booking : bookings){
            String newCar = booking.Car__c;
            String oldCar = oldBookingMap.get(booking.Id).Car__c;
            Datetime newStartDate = booking.Start_Date_Time__c;
            Datetime oldStartDate = oldBookingMap.get(booking.Id).Start_Date_Time__c;
            Datetime newEndDate = booking.End_Date_Time__c;
            Datetime oldEndDate = oldBookingMap.get(booking.Id).End_Date_Time__c;

            if(newCar != oldCar || newStartDate != oldStartDate || newEndDate != oldEndDate){
                bookingsToValidate.add(booking);
            }
        }

        if(!bookingsToValidate.isEmpty()){
            BookingTriggerHandlerService.validateBookingOverlap(bookingsToValidate);
        }
    }

    override public void afterUpdate() {
       BookingTriggerHandlerService.updateTotalBookingValueForCar((List<Booking__c>)Trigger.new, (Map<Id,Booking__c>)Trigger.oldMap);
    }
}