force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Final_Booking_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Booking_Price__c</fullName>
    <description>This booking price is based on applying discount and adjustment</description>
    <label>Final Booking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Total_Bookings_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Bookings_Value__c</fullName>
    <label>Total Bookings Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
                <default>true</default>
                <label>Success</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Late Fee</fullName>
            </value>
            <value>
                <fullName>Damage Charge</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Thresholds__mdt/System_Thresholds__mdt.object-meta.xml
<CustomObject>
    <label>System Threshold</label>
    <pluralLabel>System Thresholds</pluralLabel>
</CustomObject>

force-app/main/default/objects/System_Thresholds__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BookingTriggerTest.cls
@IsTest
public with sharing class BookingTriggerTest {
   
    //data setup
    @TestSetup
    static void makeData(){
        //create contacts
        TestDataFactory.createContacts(2);
        //create cars
        TestDataFactory.createCars(2);
    }

    @IsTest 
    static void testAfterBookingClosed(){
        Car__c carRec = [select id, Total_Bookings_Value__c from Car__c limit 1];
        Contact contactRec = [select id from Contact limit 1];

        //Create new booking
        Booking__c bookingRec = new Booking__c(Car__c = carRec.Id, Customer__c = contactRec.Id, 
        Start_date_time__c = datetime.now().addDays(1),
        End_date_time__c = datetime.now().addDays(3),
        Status__c = Constants.BOOKING_PENDING_STATUS,
        payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
        Final_Booking_Price__c = 200);

        insert bookingRec;

        //create payment - security deposit : 20% of final booking price
        System_Thresholds__mdt securityDepositThr = System_Thresholds__mdt.getInstance(Constants.SECURITY_DEPOSIT_THRESHOLD);
        Decimal securityDepositPercent = Decimal.valueOf(securityDepositThr.value__c)/100;
        Decimal securityDepositAmount = securityDepositPercent * bookingRec.Final_Booking_Price__c;

        Payment_Transaction__c securityPayment = new Payment_Transaction__c(Booking__c = bookingRec.Id, Amount__c = securityDepositAmount,
                                                                            Status__c = Constants.SUCCESS, Type__c = Constants.TYPE_SECURITY_DEPOSIT,
                                                                            Transaction_Date__c = datetime.now()
                                                                            );

        //create payment - rental payment
        Payment_Transaction__c rentalPayment = new Payment_Transaction__c(Booking__c = bookingRec.Id, Amount__c = bookingRec.Final_Booking_Price__c,
                                                                          Status__c = Constants.SUCCESS, Type__c = Constants.TYPE_INITIAL_PAYMENT,
                                                                          Transaction_Date__c = datetime.now());


        List<Payment_Transaction__c> payments = new List<Payment_Transaction__c>{securityPayment, rentalPayment};
        insert payments;

        //update booking status as closed. 
        Test.startTest();
            bookingRec.Status__c = Constants.BOOKING_CLOSED_STATUS;
            update bookingRec;
        Test.stopTest();

        //assert
        Car__c updatedCar = [select id, Total_Bookings_Value__c from Car__c where Id = :carRec.Id];
        Decimal expectedBookingValue = bookingRec.Final_Booking_Price__c;
        Decimal actualBookingValue = updatedCar.Total_Bookings_Value__c;
        system.Assert.areEqual(expectedBookingValue, actualBookingValue, 'Car Booking value is not updated.');
    }

    @IsTest
    static void testValidateBookingOverlapForInsert(){
        Car__c car = [select id from car__c limit 1];
        Contact con = [select id from Contact limit 1];

        //create first booking

        Booking__c firstBooking = new Booking__c(
                 Customer__c = con.Id,
                 Car__c = car.Id,
                 Start_Date_Time__c = Datetime.now().addDays(1), //Ex : 01 Jan , start date : 02 Jan and End Date : 04 Jan
                 End_Date_Time__c = Datetime.now().addDays(3),
                 Status__c = CONSTANTS.BOOKING_PENDING_STATUS,
                 payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
                 Final_Booking_Price__c = 200.00 //rental rate of car * duration of booking
        );
        insert firstBooking;

        //no overlap

        //create second booking

        Booking__c secondBooking = new Booking__c(
                 Customer__c = con.Id,
                 Car__c = car.Id,
                 Start_Date_Time__c = Datetime.now().addDays(4), //Ex : today - 01 Jan , start date : 05 Jan and End Date : 07 Jan
                 End_Date_Time__c = Datetime.now().addDays(6),
                 Status__c = CONSTANTS.BOOKING_PENDING_STATUS,
                 payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
                 Final_Booking_Price__c = 200.00 //rental rate of car * duration of booking
        );
        insert secondBooking;

        //create overlap booking
         Booking__c overlapBooking = new Booking__c(
                 Customer__c = con.Id,
                 Car__c = car.Id,
                 Start_Date_Time__c = Datetime.now().addDays(2), //Ex : today - 01 Jan , start date : 03 Jan and End Date : 07 Jan
                 End_Date_Time__c = Datetime.now().addDays(6),
                 Status__c = CONSTANTS.BOOKING_PENDING_STATUS,
                 payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
                 Final_Booking_Price__c = 200.00 //rental rate of car * duration of booking
        );
        try{
            insert overlapBooking;
        }catch(DMLException ex){
            String actualErrorMessage = ex.getMessage();
            String expectedErrorMessage = System.Label.Booking_Overlap_Message;
            System.Assert(actualErrorMessage.contains(expectedErrorMessage), 'Booking Dates Overlap is not working');
        }

    }


     @IsTest
    static void testValidateBookingOverlapForUpdate(){
        Car__c car = [select id from car__c limit 1];
        Contact con = [select id from Contact limit 1];

        //create first booking

        Booking__c firstBooking = new Booking__c(
                 Customer__c = con.Id,
                 Car__c = car.Id,
                 Start_Date_Time__c = Datetime.now().addDays(1), //Ex : 01 Jan , start date : 02 Jan and End Date : 04 Jan
                 End_Date_Time__c = Datetime.now().addDays(3),
                 Status__c = CONSTANTS.BOOKING_PENDING_STATUS,
                 payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
                 Final_Booking_Price__c = 200.00 //rental rate of car * duration of booking
        );
        insert firstBooking;

        //no overlap

        //create second booking

        Booking__c secondBooking = new Booking__c(
                 Customer__c = con.Id,
                 Car__c = car.Id,
                 Start_Date_Time__c = Datetime.now().addDays(4), //Ex : today - 01 Jan , start date : 05 Jan and End Date : 07 Jan
                 End_Date_Time__c = Datetime.now().addDays(6),
                 Status__c = CONSTANTS.BOOKING_PENDING_STATUS,
                 payment_status__c = Constants.BOOKING_PAYMENT_PENDING,
                 Final_Booking_Price__c = 200.00 //rental rate of car * duration of booking
        );
        insert secondBooking;


        //update dates of second booking. 
        secondBooking.Start_Date_Time__c = Datetime.now().addDays(2); ////Ex : today - 01 Jan , start date : 03 Jan 

        try{
            update secondBooking;
        }catch(DMLException ex){
            String actualErrorMessage = ex.getMessage();
            String expectedErrorMessage = System.Label.Booking_Overlap_Message;
            System.Assert(actualErrorMessage.contains(expectedErrorMessage), 'Booking Dates Overlap is not working');
        }

    }


}