force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Review_ID__c.field-meta.xml
<CustomField>
    <fullName>Review_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Review__c.Booking__c</field>
            <operation>equals</operation>
            <valueField>$Source.Related_Booking__c</valueField>
        </filterItems>
        <filterItems>
            <field>Review__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.ContactId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>REV-{0000}</displayFormat>
        <label>Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Booking__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewTriggerTest.cls
@isTest
public with sharing class ReviewTriggerTest {
    
    @testsetup
    static void makeData(){
        List<Contact> conList =  TestDataFactory.createContacts(1);
        List<Car__c> carList = TestDataFactory.createCars(1);
        List<Booking__c> bookingList = TestDataFactory.createBookings(1,conList,carList);
    }

    @IsTest
    public static void testInsertReviewTriggerHandlerForNegativeRating(){
            List<Contact> conList = [select id from contact];
            List<Booking__c> bookingList = [select id from Booking__c];
            
            List<Review__c> reviewList = TestDataFactory.createReviews(1,conList,bookingList,2);
        
            //validate sharing record is created. 
            List<Booking__share> bookingShareRec = [select parentId from Booking__share 
                                                    where parentId = :bookingList[0].Id];
        
            System.assert(bookingShareRec.size() > 0, 'Negative review record is not shared successfully');

            List<Case> caseList = [select id from case where Review_ID__c = :reviewList[0].Id];
            
            System.assert(caseList.size() > 0, 'Negative review case record is not created');

    }

    @isTest
    public static void testUpdateReviewTriggerHandlerForNegativeRating(){
        List<Contact> conList = [select id from contact];
        List<Booking__c> bookingList = [select id from Booking__c];
        List<Review__c> reviewList = TestDataFactory.createReviews(1,conList,bookingList,5);
        Review__c reviewRec = reviewList[0];
        reviewRec.Rating__c = 2;
        update reviewRec;

        //validate sharing record is created. 
        List<Booking__share> bookingShareRec = [select parentId from Booking__share 
                                                    where parentId = :bookingList[0].Id];
        
        System.assert(bookingShareRec.size() > 0, 'Negative review record is not shared successfully');

        List<Case> caseList = [select id from case where Review_ID__c = :reviewRec.Id];
            
        system.assert(caseList.size() > 0, 'Negative review case record is not created');
    }

    @isTest
    public static void testInsertForAverageCarRating(){
        List<Contact> conList = [select id from contact];
        List<Booking__c> bookingList = [select id from Booking__c];
        List<Review__c> firstReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);
        List<Review__c> secondReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);
        List<Car__c> carList = [select id,Average_Rating__c from Car__c];
        Integer expectedAverageRating = 5; //(5 + 5)/2
        Integer actualAverageRating = Integer.valueOf(carList[0].Average_Rating__c);
        System.Assert.areEqual(expectedAverageRating,actualAverageRating,'Car Average Rating is not calculated');
    }

    @isTest
    public static void testUpdateForAverageCarRating(){
        List<Contact> conList = [select id from contact];
        List<Booking__c> bookingList = [select id from Booking__c];
        List<Review__c> firstReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);
        List<Review__c> secondReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);

        //update the first review to trigger the update trigger
        firstReviewList[0].Rating__c = 3;
        update firstReviewList;

        List<Car__c> carList = [select id,Average_Rating__c from Car__c];
        Integer expectedAverageRating = 4; //(5 + 3)/2
        Integer actualAverageRating = Integer.valueOf(carList[0].Average_Rating__c);
        System.Assert.areEqual(expectedAverageRating,actualAverageRating,'Car Average Rating is not calculated');
    }

    @isTest
    public static void testDeleteForAverageCarRating(){
        List<Contact> conList = [select id from contact];
        List<Booking__c> bookingList = [select id from Booking__c];
        List<Review__c> firstReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);
        List<Review__c> secondReviewList = TestDataFactory.createReviews(1,conList,bookingList,5);

        //delete the first review to trigger the delete trigger
        delete firstReviewList;

        List<Car__c> carList = [select id,Average_Rating__c from Car__c];
        Integer expectedAverageRating = 5; //(5)/1
        Integer actualAverageRating = Integer.valueOf(carList[0].Average_Rating__c);
        System.Assert.areEqual(expectedAverageRating,actualAverageRating,'Car Average Rating is not calculated');
    }

   
}