force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>REV-{0000}</displayFormat>
        <label>Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Booking__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CarReviewController.cls
public with sharing class CarReviewController {
    
    @AuraEnabled(cacheable=true)
    public static ReviewWrapper getCarReview(Id carId){

    // Get car's average rating
      Car__c car = [
        SELECT Id, Average_Rating__c
        FROM Car__c
        WHERE Id = :carId
        LIMIT 1
      ];
    Decimal averageRating = 0;
     if(car.Average_Rating__c == null || car.Average_Rating__c == 0){
        averageRating = 0;
      }else{
        averageRating = car.Average_Rating__c;
      }


       // Get all reviews for distribution calculation
      List<Review__c> allReviews = [
        SELECT Id, Rating__c, Comments__c, CreatedDate, Booking__r.Car__c
        FROM Review__c
        WHERE Booking__r.Car__c = :carId
        ORDER BY CreatedDate DESC
      ];

      Integer tototalReviews = allReviews.size();
    

    //distribution
    Map<Integer,Integer> ratingDistribution = new Map<Integer,Integer>();
    for(Integer i = 1 ; i<=5 ; i++){
        ratingDistribution.put(i,0); //ratingDistribution = {1:0,2:0,3:0,4:0,5:0}
    }

    for(Review__c review : allReviews){
        Integer rating = (Integer)review.Rating__c;
        Integer ratingDistributionValue = ratingDistribution.get(rating);
        ratingDistributionValue = ratingDistributionValue +1;
        ratingDistribution.put(rating,ratingDistributionValue);
    }

    ReviewWrapper reviewWrapper = new ReviewWrapper(allReviews,ratingDistribution,tototalReviews,averageRating);
    return reviewWrapper;
}


    
public class ReviewWrapper {
    @AuraEnabled
    public List<Review__c> reviews;
    @AuraEnabled
    public Map<Integer, Integer> ratingDistribution;
    @AuraEnabled
    public Integer totalReviews;
    @AuraEnabled 
    public Decimal averageRating;
    
    public ReviewWrapper(
      List<Review__c> reviews,
      Map<Integer, Integer> ratingDistribution,
      Integer totalReviews,
      Decimal averageRating
    ) {
      this.reviews = reviews;
      this.ratingDistribution = ratingDistribution;
      this.totalReviews = totalReviews;
      this.averageRating = averageRating;
    }
  }


}

//car --> multiple booking --> one booking can have multiple reviews