force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
                <isActive>false</isActive>
                <label>Reserved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Description__c.field-meta.xml
<CustomField>
    <fullName>Car_Description__c</fullName>
    <label>Car Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Family__c.field-meta.xml
<CustomField>
    <fullName>Car_Family__c</fullName>
    <label>Car Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
                <default>true</default>
                <label>Sedan</label>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Sports Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transmission_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
                <default>true</default>
                <label>Petrol</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Biodiesel</fullName>
            </value>
            <value>
                <fullName>Gasoline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Mileage_Limit_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Limit_Per_Day__c</fullName>
    <label>Mileage Limit Per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Number_of_Seats__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Seats__c</fullName>
    <label>Number of Seats</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/PickupLocation__c.field-meta.xml
<CustomField>
    <fullName>PickupLocation__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Primary_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image_Url__c</fullName>
    <label>Primary Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Rental_Rate_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Rental_Rate_Per_Day__c</fullName>
    <label>Rental Rate Per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Transmission_Type__c.field-meta.xml
<CustomField>
    <fullName>Transmission_Type__c</fullName>
    <label>Transmission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
                <default>true</default>
                <label>Automatic</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/carTileListController.cls
public with sharing class carTileListController {
    
    public class Filters{
        @AuraEnabled
        public String searhKey{get;set;}
        @AuraEnabled
        public Integer maxSeats{get;set;}
        @AuraEnabled
        public Date startDate{get;set;}
        @AuraEnabled
        public Date endDate{get;set;}
        @AuraEnabled
        public Decimal maxRentalRate{get;set;}
        @AuraEnabled
        public Decimal minRating{get;set;}
        @AuraEnabled
        public String pickupLocation{get;set;}
        @AuraEnabled
        public List<String> transmissionType{get;set;}
        @AuraEnabled
        public List<String> fuelType{get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static List<Car__c> getCars(Filters filters){
        List<String> criteria = new List<String>();
        String key,pickupLocation;
        Decimal maxSeat, maxRentalRate, minRating;
        List<String> transmissionType,fuelType;
        //default filter criteria
       String availableCars = Constants.AVAILABLE_CARS;
       criteria.add('Availability_Status__c = :availableCars');

       //Optional Parameters
        if(String.isNotBlank(filters.searhKey)){
            key = '%' + filters.searhKey + '%';
            criteria.add('Name like :key');
        }
        if(filters.maxSeats != null){
            maxSeat = filters.maxSeats;
            criteria.add('Number_of_Seats__c <= :maxSeat');
        }
        if(filters.maxRentalRate != null){
            maxRentalRate = filters.maxRentalRate;
            criteria.add('Rental_Rate_Per_Day__c <= :maxRentalRate');
        }

        if(filters.minRating != null){
            minRating = filters.minRating;
            if(minRating == 0){
                criteria.add('(Average_Rating__c = null OR Average_Rating__c >= 0)');  
            }
            else{
                criteria.add('Average_Rating__c >= :minRating');
            }
        }
        if(String.isNotBlank(filters.pickupLocation)){
            pickupLocation = filters.pickupLocation ;
            criteria.add('PickupLocation__c = :pickupLocation');
        }
        
         //check for transmission type
        if(filters.transmissionType != null && !filters.transmissionType.isEmpty()){
            transmissionType = filters.transmissionType;
            criteria.add('Transmission_Type__c IN :transmissionType');
        }

           //check for fuel type
        if(filters.fuelType != null && !filters.fuelType.isEmpty()){
            fuelType = filters.fuelType;
            criteria.add('Fuel_Type__c IN :fuelType');
        }

        //start date and end date --> so that we can avaoid to fetch the cars which already have booking in those dates. 
        Datetime startDateTime = Datetime.newInstance(filters.startDate, Time.newInstance(0, 0, 0, 0));
        Datetime endDateTime = Datetime.newInstance(filters.endDate, Time.newInstance(23, 59, 59, 0));

        //get booking between the start date and end date and we are excluding the cars which are having the booking
        Set<id> bookedCarId  = new Set<id>();
        for(Booking__c booking : [select id,car__c from Booking__c where start_date_time__c >= :startDateTime and end_date_time__c <= :endDateTime ]){
            bookedCarId.add(booking.car__c);
        }
        if(!bookedCarId.isEmpty()){
            criteria.add('id not in :bookedCarId');
        }

        //prepare your dynamic query 
                String queryToGetCars = 'SELECT Id,Average_Rating__c,Availability_Status__c,Car_Description__c,Car_Family__c,Fuel_Type__c,Make__c,Mileage_Limit_Per_Day__c,Model__c,Name,Number_of_Seats__c,PickupLocation__c,Primary_Image_Url__c,Rental_Rate_Per_Day__c,Transmission_Type__c  FROM Car__c';
                String whereClause =  ' where ' + String.Join(criteria, ' AND ');
                queryToGetCars = queryToGetCars + whereClause;
                queryToGetCars += ' order by Name ';
                System.debug('queryToGetCars ' + queryToGetCars);
                return Database.query(queryToGetCars);
    }

}