force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Amount__c</fullName>
    <inlineHelpText>Initial Payment or Partial Payment summary</inlineHelpText>
    <label>Total Paid Amount</label>
    <summarizedField>Payment_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment_Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Success</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment_Transaction__c.Type__c</field>
        <operation>equals</operation>
        <value>Initial Payment, Partial Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Transaction__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Total_Bookings_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Bookings_Value__c</fullName>
    <label>Total Bookings Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QueuableTotalCarValue.cls
public with sharing class QueuableTotalCarValue implements Queueable{
    private Set<Id> carIds;
    public QueuableTotalCarValue(Set<Id> carIds){
        this.carIds = carIds;
    }
    public void execute(QueueableContext qc){
        //use aggregate query to calculate total Booked value
        Map<Id,Decimal> carTotalValues = new Map<Id,Decimal>();
        List<Car__c> carList = new List<Car__c>();
        for(AggregateResult agr : [select Car__c carId, sum(Total_Paid_Amount__c) totalValue 
                                    from Booking__c where Status__c  = :Constants.BOOKING_CLOSED_STATUS 
                                    AND Car__c in :carIds
                                    group by Car__c ]){

             Id carId =  (Id)  agr.get('carId');
             Decimal totalValue = (Decimal) agr.get('totalValue') ;
             carTotalValues.put(carId,totalValue);                       
        }

        for(Id carId : carIds){
            Car__c car = new Car__c(Id = carId);
            car.Total_Bookings_Value__c = carTotalValues.get(carId);
            carList.add(car);
        }

        try {
            if(carList.size() > 0){
                update carList;
            }
        } catch (Exception ex) {
            //log error to the apex logs
              system.debug(ex.getMessage());
              Log logger = Log.get();
              logger.publish(ex.getMessage());
        }
    }
}