force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
                <isActive>false</isActive>
                <label>Reserved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Description__c.field-meta.xml
<CustomField>
    <fullName>Car_Description__c</fullName>
    <label>Car Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Family__c.field-meta.xml
<CustomField>
    <fullName>Car_Family__c</fullName>
    <label>Car Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
                <default>true</default>
                <label>Sedan</label>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Sports Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transmission_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
                <default>true</default>
                <label>Petrol</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Biodiesel</fullName>
            </value>
            <value>
                <fullName>Gasoline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/PickupLocation__c.field-meta.xml
<CustomField>
    <fullName>PickupLocation__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Primary_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image_Url__c</fullName>
    <label>Primary Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Rental_Rate_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Rental_Rate_Per_Day__c</fullName>
    <label>Rental Rate Per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Transmission_Type__c.field-meta.xml
<CustomField>
    <fullName>Transmission_Type__c</fullName>
    <label>Transmission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
                <default>true</default>
                <label>Automatic</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarAvailabilityRestApiService.cls
@Restresource(urlMapping='/v1/cars/available/*')
global with sharing class CarAvailabilityRestApiService {
    
    @HttpGet
    global static responseWrapper getAvailableCars() {
        //get the query parameters 
        RestRequest req = RestContext.request;
        //start date
        Date startDate = Date.valueOf(req.params.get('startDate'));
        //end date
        Date endDate = Date.valueOf(req.params.get('endDate'));
        //Fuel type
        String fuelType = req.params.get('fuelType');
        //transmissin type
        String transmissionType = req.params.get('transmissionType');
        //Location
        String location = req.params.get('location');

        //validations
        if(startDate == null || endDate == null){
            return new responseWrapper(false, 'Start date and end date are required', null);
        }
        if (String.isBlank(location)) {
            return new responseWrapper(false, 'Location is required', null);
        }
        //start date must be less than end date
        if(startDate > endDate){
            return new responseWrapper(false, 'Start date must be less than end date', null);
        }

        Set<id> bookedCarId  = new Set<id>();
        Datetime startDateTime = Datetime.newInstance(startDate, Time.newInstance(0, 0, 0, 0));
        Datetime endDateTime = Datetime.newInstance(endDate, Time.newInstance(23, 59, 59, 0));
        //get booking records for the same date range
        for(Booking__c booking :[select id,car__c from Booking__c where start_date_time__c >= :startDateTime and end_date_time__c <= :endDateTime]){
            bookedCarId.add(booking.car__c);
        }

        //build the query for available cars -- dynamic
        String available = CONSTANTS.AVAILABLE_CARS;
        String query = 'select id, name, rental_rate_per_day__c, primary_image_url__c, fuel_type__c, Car_Family__c, transmission_type__c,car_description__c,PickupLocation__c from car__c';
        query = query + ' where id not in :bookedCarId and PickupLocation__c = :location and Availability_Status__c = :available';

        //Optional Parameters
        if(String.isNotBlank(fuelType)){
            query = query + ' and fuel_type__c = :fuelType';
        }
        if(String.isNotBlank(transmissionType)){
            query = query + ' and transmission_type__c = :transmissionType';
        }
       
        //execute query
        List<Car__c> cars = Database.query(query);

        if(cars.isEmpty()){
            return new responseWrapper(false, 'No cars available for the given date range', null);
        }
        
        //prepare response
        List<carResponseWrapper> carResponseWrappers = new List<carResponseWrapper>();
        for(Car__c car : cars){
           carResponseWrapper carResponse = new carResponseWrapper(car);
           carResponseWrappers.add(carResponse);
        }
        return new responseWrapper(true, 'Available cars', carResponseWrappers);

    }

    global class responseWrapper {
        public Boolean success;
        public String message;
        public List<carResponseWrapper> cars;

        public responseWrapper(Boolean success, String message, List<carResponseWrapper> cars){
            this.success = success;
            this.message = message;
            this.cars = cars;
        }
    }

    global class carResponseWrapper {
        public string id;
        public string name;
        public Decimal rentalRate;
        public string imageUrl;
        public string fuelType;
        public string family;
        public string transmissionType;
        public string location;
        public string description;

        public carResponseWrapper(Car__c car){
            this.id = car.Id;
            this.name = car.Name;
            this.rentalRate = car.Rental_Rate_Per_Day__c;
            this.imageUrl = car.Primary_Image_Url__c;
            this.fuelType = car.Fuel_Type__c;
            this.family = car.Car_Family__c;
            this.transmissionType = car.Transmission_Type__c;
            this.location = car.PickupLocation__c;
            this.description = car.Car_Description__c;
        }

    }
}