force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Car__c.Availability_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CarAvailabilityRestApiServiceTest.cls
@isTest
public with sharing class CarAvailabilityRestApiServiceTest {

    @TestSetup
    static void makeData(){
        List<Contact> conList =  TestDataFactory.createContacts(2);
        List<Car__c> carList = TestDataFactory.createCars(4);
        List<Booking__c> bookingList = TestDataFactory.createBookings(1,conList,carList);
    }

    @isTest
    static void testGetAvailableCars(){

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        RestContext.request = req;
        RestContext.response = res;

      
        //  Date todaysDate = date.today();
        //  Date startDate = todaysDate.addDays(1);
        //  Date endDate = todaysDate.addDays(3); 
        //  String startDateString = startDate.format('yyyy-MM-dd');
        //  String endDateString = endDate.format('yyyy-MM-dd');
         

        req.params.put('startDate',formatDate(date.today().addDays(10)));
        req.params.put('endDate',formatDate(date.today().addDays(30)));
        req.params.put('location','Pune');
        req.params.put('fuelType','Petrol');
        req.params.put('transmissionType','Automatic');

        CarAvailabilityRestApiService.responseWrapper response = CarAvailabilityRestApiService.getAvailableCars();
        Test.stopTest();

        System.Assert.areEqual(true,response.success);
    }

    private static string formatDate(Date inpDate){
          return inpDate.year() + '-' + inpDate.month() + '-' + inpDate.day();  
    }
}