force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BOOK-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Final_Booking_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Booking_Price__c</fullName>
    <description>This booking price is based on applying discount and adjustment</description>
    <label>Final Booking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <formula>Final_Booking_Price__c *  (VALUE($CustomMetadata.System_Thresholds__mdt.Security_Deposit_Percentage.Value__c) / 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
                <default>true</default>
                <label>Success</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Late Fee</fullName>
            </value>
            <value>
                <fullName>Damage Charge</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTransactionTriggerHandlerService.cls
public with sharing class PaymentTransactionTriggerHandlerService {
    
    public static void handlePaymentTransactions(List<Payment_Transaction__c> paymentTransactions){

        //get all the affected booking id
        Set<Id> bookingIds = new Set<Id>();
        for(Payment_Transaction__c paymentTransaction : paymentTransactions){
            bookingIds.add(paymentTransaction.Booking__c);
        }

        //Parent --> child relationship query
        //bookingId to list of related Payment_Transaction__c
       Set<String> paymentType = new Set<String>();
       paymentType.add(Constants.TYPE_INITIAL_PAYMENT);
       paymentType.add(Constants.TYPE_SECURITY_DEPOSIT);
        paymentType.add(Constants.TYPE_PARTIAL_PAYMENT);

        List<Booking__c> updateBookingRecords = new List<Booking__c>();

       List<Booking__c> bookingList = [SELECT Id,Status__c,Payment_Status__c,Final_Booking_Price__c,Security_Deposit__c,
       (select id,Amount__c,Type__c,Status__c from Payment_Transactions__r where status__c = :Constants.SUCCESS and type__c in :paymentType) 
       FROM Booking__c where id in :bookingIds];
       System.debug('bookingList'+bookingList);
       
       for(Booking__c booking : bookingList){
         Decimal initialPayment = 0;
         Decimal partialPayment = 0;
         Decimal securityPayment = 0;

         for(Payment_Transaction__c paymentTransaction : booking.Payment_Transactions__r){
             if(paymentTransaction.Type__c == Constants.TYPE_INITIAL_PAYMENT){
                initialPayment = initialPayment + paymentTransaction.Amount__c;
             }
              else if(paymentTransaction.Type__c == Constants.TYPE_PARTIAL_PAYMENT){
                partialPayment = partialPayment + paymentTransaction.Amount__c;
             }
              else if(paymentTransaction.Type__c == Constants.TYPE_SECURITY_DEPOSIT){
                securityPayment = securityPayment + paymentTransaction.Amount__c;
             }
         }

         System.debug('initialPayment'+initialPayment);
         System.debug('partialPayment'+partialPayment);
         System.debug('securityPayment'+securityPayment);

         //payment status : Final Booking Price >= Initial Payment + Partial Payment && security deposit >=  securityPayment--> paid , else partially paid
         //booking status : Exisint booking status = Pending && initialPayment,partialPayment,securityPayment > 0 --> Confirmed. 
         booking.Payment_Status__c = calculatePaymentStatus(initialPayment, partialPayment, securityPayment,booking.Final_Booking_Price__c,booking.Security_Deposit__c);
         booking.Status__c = calculateBookingStatus(initialPayment, partialPayment, securityPayment,booking.Status__c);
         updateBookingRecords.add(booking);
       }

        if(updateBookingRecords.size() > 0){
           try {
            update updateBookingRecords;
           } catch (Exception e) {
               system.debug('Error occured while updating the payment status and booking status '+ e.getMessage());
               Log logger = Log.get();
               logger.publish('Error while updating Payment and Booking Status ' + e.getMessage());
           }
        }
    }

    public static String calculatePaymentStatus(Decimal initialPayment, Decimal partialPayment, Decimal securityPayment,
                                                Decimal finalBookingPrice, Decimal securityDeposit){

        if(initialPayment == 0 && securityDeposit == 0 && finalBookingPrice == 0){
            return constants.BOOKING_PAYMENT_PENDING;
        }                                            
        Decimal totalRentalPayment =    initialPayment + partialPayment;
        Boolean isTotalRentalPaymentCompleted = finalBookingPrice <= totalRentalPayment;
        Boolean isSecurityDepositCompleted = securityDeposit <= securityPayment;

        if(isTotalRentalPaymentCompleted && isSecurityDepositCompleted){
            return constants.BOOKING_PAID;
        }else{
             return constants.BOOKING_PARTIAL_PAID;
        }
    }

    public static String calculateBookingStatus(Decimal initialPayment, Decimal partialPayment, Decimal securityPayment,String currentBookingStatus){
        if(currentBookingStatus == constants.BOOKING_PAYMENT_PENDING && (initialPayment > 0 || partialPayment > 0 || securityPayment > 0)){
            return constants.BOOKING_CONFIRM_STATUS;
        }else{
            return currentBookingStatus;
        }
    }
        
}