force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Image__c.field-meta.xml
<CustomField>
    <fullName>Car_Image__c</fullName>
    <formula>IF( ISBLANK( Primary_Image_Url__c ) , IMAGE(&apos;/resource/CarOnRentalLogo&apos;,&quot;Car On Rental Logo&quot;,200,200),IMAGE(Primary_Image_Url__c, Name , 400,400))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Car Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car_Image__c/Car_Image__c.object-meta.xml
<CustomObject>
    <label>Car Image</label>
    <nameField>
        <displayFormat>IMG-{0000}</displayFormat>
        <label>Image Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Image__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Images</relationshipLabel>
    <relationshipName>Car_Images</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Image__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car_Image__c/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Image</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/carImageController.cls
public with sharing class carImageController {
   
    @AuraEnabled 
    public static void createFile(
        String documentId,
        String recordId,
        Boolean isPrimaryImage
    ){
        //get the latest content version from the content document. 

        List<ContentVersion> contentVersion = [
            SELECT Id,ContentDocumentId from ContentVersion 
            where IsLatest = true and ContentDocumentId = :documentId
            order by CreatedDate desc limit 1
        ];
        if(contentVersion.isEmpty()){
           throw new AuraHandledException('Content version not found for content document id ' + isPrimaryImage);
        }

        //insert record in carImage
        Car_Image__c carImage = new Car_Image__c(
            Car__c = recordId,
            Image_Url__c =  '/sfc/servlet.shepherd/version/download/' + contentVersion[0].Id
        );
        if(isPrimaryImage){
            carImage.Primary_Image__c = true;
        }
        try {
            insert carImage;
        } catch (Exception ex) {
            System.debug(ex.getMessage());
             Log logger = Log.get();
            logger.publish(ex.getMessage());
        }
    }

      @AuraEnabled(cacheable=true)
  public static List<Car_Image__c> getCarImages(Id productId) {
    try {
      return [
        SELECT id, Car__r.Name, Image_Url__c, Primary_Image__c
        FROM Car_Image__c
        WHERE Car__c = :productId
        WITH USER_MODE
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}